apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prom-loki-token
  namespace: promtail
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: prom-loki-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: prom-loki-token-{{ .Values.clusterName }}
